CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Werror -pedantic -O2
INCLUDES = -I../common -I../UserCommon -I.
LIBS = -ldl

TARGET = test_map_parsing
SOURCES = test_map_parsing.cpp GameRunner.cpp SimulationResults.cpp

OBJECTS = $(SOURCES:.cpp=.o)

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET) $(LIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)

.PHONY: clean 